require "thor"
require "json"
require "yaml"
require "net/http"
require "uri"
require "fileutils"
require "time"

require_relative "fizzy/error"
require_relative "fizzy/config"
require_relative "fizzy/client"
require_relative "fizzy/response"
require_relative "fizzy/commands/base"
require_relative "fizzy/commands/auth"
require_relative "fizzy/commands/identity"
require_relative "fizzy/cli"
